- BE/src/main/resources/application.properties
Fixed #20 issue: [BE] 테스트 DB 접속용 설정 추가
테스트용 DB 명만 TB_를 붙이시면 되고, 내부 TABLE은 Deploy DB와 동일하게 유지하였습니다.
> [#20] Feat: Test DB 접속 설정 추가 및 Test DB로 접속하도록 변경

- .gitignore
Fixed #22 전체 디렉토리에 대한 gitignore 파일 추가
> [#22] Chore : gitignore 파일 추가

- .github/workflows/test-workflow.yml
> [#36] Feat: 테스트용 workflow 생성

- .github/workflows/test-workflow.yml
> [#36] Feat: heroku login을 하도록 workflow 수정

- .github/workflows/test-workflow.yml
복붙을 실수했습니다.
JK에게 잘못된 KEY 값을 드려서 그에 맞게 수정했어요.
> [#36] Feat: heroku api key의 secret 값을 HEROKU_API_TOKEN으로 수정

- .github/workflows/test-workflow.yml
> [#36] Feat: heroku deploy 테스트용 step 작성

- .github/workflows/test-workflow.yml
이제 거의 다 완료된 것 같습니다.
build는 아마 실패 할 것 같아요.
> [#36] Fix: heroku app을 생성하지 않고 push해서 app을 생성하고 application name을 지정

- .github/workflows/test-workflow.yml
> [#36] Fix: docker image를 올리는 스크립트를 git subtree push를 이용하도록 수정

- .github/workflows/test-workflow.yml
> [#36] Fix: git subtree 명령어에 force 옵션이 없어서, 제거

- .github/workflows/test-workflow.yml
헤로쿠 로그인을 안해줘서 거부됬네요.
다시 한 번 시도해보겠습니다.
> [#36] Fix: heroku login 하는 부분이 필요해서 추가

- .github/workflows/test-workflow.yml
😱 이게 무슨짓인지 모르겠습니다.
개인 repo를 파서 할 걸 싶기도 합니다...
> [#36] Fix: Login의 문제가 아니라 환경변수명이 잘못되어서 수정

- .github/workflows/test-workflow.yml
오류 메시지를 읽어보니, heroku remote repository를 못찾는데... 한 번 처리가 되는지 보려고 합니다.
> [#36] Fix: 예제와 동일하게 HEROKU_APP_NAME을 환경변수로 추출

- .github/workflows/test-workflow.yml
> [#36] Fix: 오타 수정 codesqaud → codesquad

- BE/build.gradle
- BE/src/main/java/com/codesquad/team1/signup/config/JasyptConfig.java
- BE/src/main/resources/application.properties
- Jasypt-Spring-Boot-Starter 의존성을 추가하였습니다.
- Jasypt 설정을 추가하였습니다.
- Bean을 직접 설정해주었습니다. Key값은 GitHub Setting의 Secret을 사용해야 할 것 같은데, 고민입니다.
- Close #13 Issue.
DB 접속 암호 변경되었습니다.
> [#13] 데이터 베이스 접속 정보 암호화

- FE/scss/common.scss
> [#2] Fix: SCSS 뎁스 2단계로 제한

- BE/src/main/java/com/codesquad/team1/signup/controller/ApiUserController.java
- BE/src/main/java/com/codesquad/team1/signup/repository/UserRepository.java
resolved #6
- 메소드명은 상의해서 변경하도록 하겠습니다.
- 응답 객체를 통일하는게 좋을까 하는 생각이 들어요. 어디선가 ResponseEntity를 전달하는 방식을 본 적이 있었어서요.
- 현재는 postman으로 localhost:8080/users/duplicate/email/dionte3st@gmail.com 이런식으로 테스트하고 있는데 문제 없을까요?
> [#6] Feat: 중복 이메일 조회 WEB API 구현

- FE/scss/common.scss
- FE/scss/variables.scss
- FE/src/signup.html
- 관심사 태그가 여러 줄이 될 경우 레이아웃이 깨지는 문제 수정
- 중복 코드 제거, 일관성 있게 코드 다듬기
- 약간의 디자인 수정~
- Close #58
> [#58] Fix: 관심사 태그 레이아웃 수정

- BE/src/main/java/com/codesquad/team1/signup/controller/ApiUserController.java
- BE/src/main/java/com/codesquad/team1/signup/repository/UserRepository.java
- /users/duplicate/phone-number/{phoneNumber} 요청에 대해 parameter로 전달된 핸드폰 번호가 중복되는지 여부를 boolean으로 반환
- rebase 하고 다시 reopen 합니다.
> [#7] Feat: 중복 핸드폰 조회 API 구현

- BE/src/main/resources/application.properties
- logback 로깅을 설정하였습니다.
- logs 폴더에 log가 쌓이도록 설정하였습니다.
- Close #14 Issue.
> [#14] Feat: logback 로깅 설정

- BE/README.md
- 로깅 및 로깅 파일을 저장하도록 하였습니다.
- rolling file은 logback.xml로 설정해주어야 하는 것으로 확인했습니다.
- Close #63 issue.
> [#63] Docs: 작업한 내용 Document 업데이트

- BE/README.md
- BE/src/main/java/com/codesquad/team1/signup/constants/ValidationConstants.java
- BE/src/main/java/com/codesquad/team1/signup/controller/ApiUserController.java
- BE/src/main/java/com/codesquad/team1/signup/repository/User.java
- User 이외의 Validation이 필요할 경우를 대비, USER_ prefix를 정의하였습니다.
- 사용하지 않는 Optional import를 제거하였습니다. Fixed #62 Issue.
- validate를 User 객체에서 직접 수행하는, 객체지향적인 접근을 시도하였습니다.
- Close #78 Issue.
> [#78] User Validation 기능 구현

- .github/workflows/dev-workflow.yml
- .github/workflows/master-workflow.yml
- BE/README.md
- master/develop 별로 다른 서버에 배포될 수 있도록 하였습니다.
> [#73] Chore: 빌드 파일 수정

- BE/README.md
- BE/src/main/java/com/codesquad/team1/signup/controller/ApiUserController.java
- BE/src/main/java/com/codesquad/team1/signup/repository/User.java
- POST /users/create로 생성요청을 보냅니다.
- 객체 생성시 필요해서 setter method를 일부 추가하였습니다.
- 성공시 User 객체를 돌려줍니다.
- 실패시 에러 정보를 돌려줍니다. (추후 수정예정)
- Close #9 Issue.
> [#9] Feat: 유저 생성 기능 구현

- .github/workflows/dev-workflow.yml
- .github/workflows/master-workflow.yml
- git push --force를 이용하여 배포할 수 있도록 하였습니다.
> [#85] Fix: Auto Deploy 오류 수정

- BE/src/main/java/com/codesquad/team1/signup/controller/ApiUserController.java
- BE/src/main/java/com/codesquad/team1/signup/repository/User.java
- BE/src/main/java/com/codesquad/team1/signup/repository/UserRepository.java
feat #10 
- 포스트맨으로 테스트하는 과정에서 쿠키가 제대로 삭제되지 않아서 테스트하기 어려웠습니다. login 응답값은 예측한대로 넘어오는데 쿠키 삭제가 원활하지 않아서 Set-cookie 헤더랑 jsessionId가 유효한지 제대로된 검증은 못했습니다.
=> feature/be/show(#8)을 구현하여 위 기능과 함께 포스트맨으로 테스트했더니 정상적으로 동작하는 것을 확인했습니다. 해당 feature/be/show는 로그인 여부를 판단하는 로직이 존재합니다.
- 응답과 예외처리 발생을 어떻게 해야할지 고민이 많아서 진행이 빨리 안됐습니다. 응답 일단 구현 먼저하고 리뷰 받아서 수정해나가는 방향으로 하겠습니다.
> [#10] 로그인 기능 구현

- BE/.gitignore
- BE/README.md
- BE/build.gradle
- BE/src/main/java/com/codesquad/team1/signup/web/controller/MainController.java
- BE/src/main/resources/application.properties
- BE/src/main/resources/static/css/home.css
- BE/src/main/resources/static/css/index.css
- BE/src/main/resources/static/css/signin.css
- BE/src/main/resources/static/dist/home.bundle.js
- BE/src/main/resources/static/dist/index.bundle.js
- BE/src/main/resources/static/dist/signin.bundle.js
- BE/src/main/resources/static/home.html
- BE/src/main/resources/static/index.html
- BE/src/main/resources/static/signin.html
- FE/webpack.config.js
- FE의 dist 파일을 그대로 static에 옮겨와서 사용했습니다.
- template에 넣어주고 싶은데 넣으면 css가 안읽혀서 일단 현 상태로 진행하려고 합니다.
- logs 디렉토리 전체를 gitignore에 추가하였습니다. 
- Close #69 Issue.
- Close #75 Issue.
> [#75] FE에서 작성된 화면을 BE의 template에 적용

- FE/src/modules/fields.js
- FE/src/modules/server.js
- FE/src/modules/validation.js
- Close #21 
- 생년월일 중 만 나이 계산 에러메세지는 우선 보류입니다... 현재 능력치 부족...
- Select 태그가 기본값일때는 유저 정보에 null 값이 들어가게 만들었습니다.
> [#21] Feat: Select태그, 생년월일 유효성 검증

- BE/src/main/java/com/codesquad/team1/signup/constants/ValidationConstants.java
- Ed가 수정한 버전을 그대로 가져왔습니다.
- Fixed #92 Issue.
> [#92] Fix: 이메일 정규표현식에 문제가 있어 수정

- BE/src/main/java/com/codesquad/team1/signup/config/WebConfig.java
- 전역 설정을 통해서 Cross Origin 허용하는 방법으로 해결해보려고 시도함.
> [#101] 스프링 부트 cors 문제 구현 (테스트 필요)

- BE/src/main/java/com/codesquad/team1/signup/controller/ApiUserController.java
Closed #100
- 로그아웃 메소드를 POST로 변경했습니다.
> [#100] 로그아웃 메소드 GET=>POST로 변경

- BE/src/main/resources/application-develop.properties
- BE/src/main/resources/application-local.properties
- BE/src/main/resources/application-master.properties
- BE/src/main/resources/application.properties
- 기본적으로 local 정보를 읽어서 local 환경에서 항상 실행 가능하도록 하였습니다.
- develop branch에서 배포되는 test 서버는 develop 환경정보를 읽도록 하였습니다.
- master branch에서 배포되는 production 서버는 master 환경정보를 읽도록 하였습니다.
- 테스트 완료후 Issue는 수동 Close 하겠습니다.
#74 Issue를 참고해주세요!
> [#74] Feat: 배포환경 별 설정정보를 다르게 지정

- BE/src/main/java/com/codesquad/team1/signup/common/constants/ErrorMessages.java
- BE/src/main/java/com/codesquad/team1/signup/common/constants/ValidationConstants.java
- BE/src/main/java/com/codesquad/team1/signup/common/exception/ForbiddenException.java
- BE/src/main/java/com/codesquad/team1/signup/common/exception/UnauthorizedException.java
- BE/src/main/java/com/codesquad/team1/signup/common/response/ErrorResponse.java
- BE/src/main/java/com/codesquad/team1/signup/common/response/ValidationResponse.java
- BE/src/main/java/com/codesquad/team1/signup/common/utils/HttpSessionUtils.java
- BE/src/main/java/com/codesquad/team1/signup/domain/interest/Interest.java
- BE/src/main/java/com/codesquad/team1/signup/domain/interest/InterestRepository.java
- BE/src/main/java/com/codesquad/team1/signup/domain/user/User.java
- BE/src/main/java/com/codesquad/team1/signup/domain/user/UserRepository.java
- BE/src/main/java/com/codesquad/team1/signup/repository/Gender.java
- BE/src/main/java/com/codesquad/team1/signup/web/api/ApiUserController.java
Closed #104
Closed #109
- common 패키지를 생성하여 공통적으로 사용하는 내용들을 모아봤습니다.
- domain 클래스에서 entity 별로 폴더를 구분했습니다.
- exceptiona 패키지 명 변경했습니다
- ErrorMessages 클래스를 이용하여 에러 메세지 상수를 모았습니다.
- 브랜치명이 구려서 죄송합니닷ㅎㅎ
- 리팩토링 넘나 어려운 것
---
- 예외 처리 내용이 컨트롤러에서 많아져서 ExceptionController를 정의할까 고민입니다.
> [#104] HttpSessionUtils 클래스 생성, 패키지 변경, 아주 약간의 리팩토링

- BE/src/main/java/com/codesquad/team1/signup/api/ApiUserController.java
- BE/src/main/java/com/codesquad/team1/signup/common/config/JasyptConfig.java
- BE/src/main/java/com/codesquad/team1/signup/common/config/WebConfig.java
- BE/src/main/java/com/codesquad/team1/signup/common/utils/HttpSessionUtils.java
- BE/src/main/java/com/codesquad/team1/signup/domain/user/UserRepository.java
- BE/src/main/java/com/codesquad/team1/signup/web/MainController.java
아까 말씀드린 부분입니다.
머지 된 후 빌드된 것이 제대로 배포되는지 확인을 하려고 합니다.
> [#109] 패키지 리팩토링을 하였습니다.

- BE/src/main/java/com/codesquad/team1/signup/api/ApiUserController.java
- BE/src/main/java/com/codesquad/team1/signup/common/constants/ErrorMessages.java
- BE/src/main/java/com/codesquad/team1/signup/common/exception/BusinessException.java
- BE/src/main/java/com/codesquad/team1/signup/common/exception/ForbiddenException.java
- BE/src/main/java/com/codesquad/team1/signup/common/exception/UnauthorizedException.java
- BE/src/main/java/com/codesquad/team1/signup/common/exception/UserCreateParameterInvalidException.java
- BE/src/main/java/com/codesquad/team1/signup/domain/user/User.java
- 최상위 CustomException인 BusinessException을 생성하고 그 하위 Exception으로 구조를 변경하였습니다.
- User 생성시 validation에 실패하면 발생하는 Exception을 생성하였습니다.
> [#109] Refactor: Custom Exception 구조 생성
